name: Build cwebp

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone libwebp source
        run: |
          git clone https://github.com/webmproject/libwebp.git
          cd libwebp
          git checkout main
        shell: cmd

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Install NMAKE
        run: choco install -y ninja

      - name: Build cwebp for Windows (x64)
        run: |
          cd libwebp
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          nmake /f Makefile.vc CFG=release-static RTLIBCFG=static OBJDIR=output
        shell: cmd

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cwebp-windows-x64
          path: libwebp/output/release-static/x64/bin/cwebp.exe

  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone libwebp source
        run: |
          git clone https://github.com/webmproject/libwebp.git
          cd libwebp
          git checkout main

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make autoconf automake libtool libc6-dev libpng-dev libjpeg-dev libtiff-dev zlib1g-dev

      - name: Build cwebp for Linux x86_64
        run: |
          cd libwebp
          make -f makefile.unix CFLAGS="-O3 -fPIE" LDFLAGS="-static -pie -lm"
          strip examples/cwebp
          sudo cp examples/cwebp /usr/local/bin/cwebp

      - name: Verify static linking
        run: |
          ldd /usr/local/bin/cwebp || echo "No dynamic libraries linked (static binary)"
          file /usr/local/bin/cwebp

      - name: Upload Linux x86_64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cwebp-linux-x86_64
          path: /usr/local/bin/cwebp

  build-linux-arm:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone libwebp source
        run: |
          git clone https://github.com/webmproject/libwebp.git
          cd libwebp
          git checkout main

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make autoconf automake libtool libc6-dev libpng-dev libjpeg-dev libtiff-dev zlib1g-dev

      - name: Build cwebp for Linux ARM64
        run: |
          cd libwebp
          make -f makefile.unix CFLAGS="-O3 -fPIE" LDFLAGS="-static -pie -lm"
          strip examples/cwebp
          sudo cp examples/cwebp /usr/local/bin/cwebp

      - name: Verify static linking
        run: |
          ldd /usr/local/bin/cwebp || echo "No dynamic libraries linked (static binary)"
          file /usr/local/bin/cwebp

      - name: Upload Linux ARM64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cwebp-linux-arm64
          path: /usr/local/bin/cwebp
